let hymns=[], current=null, playing=false, timer=null, favorites=JSON.parse(localStorage.getItem('ps_favs')||'[]');
const list=document.getElementById('list'),q=document.getElementById('q'),count=document.getElementById('count');
fetch('hymns.json').then(r=>r.json()).then(x=>{hymns=x;render(x)});
function hasSolfa(h){return h.sections.some(s=>s.solfa&&s.solfa.length)}
function render(items){count.textContent=items.length+' hymns';list.innerHTML=items.map(h=>`<article class="card" onclick="openReader('${h.n}')"><div><div class="num">HYMN ${h.n}</div><h3>${h.title}</h3><small class="meta">${h.author} • ${h.tune} • ${h.status}</small>${hasSolfa(h)?'<div class="meta hasSolfa">● Sol-fa available</div>':''}</div><button class="open">Open</button></article>`).join('')}
q.oninput=e=>filterAll(e.target.value);
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let f=b.dataset.filter;let x=f==='notation'?hymns.filter(hasSolfa):f==='favorites'?hymns.filter(h=>favorites.includes(h.n)):hymns;render(x)});
function filterAll(s){s=s.toLowerCase();render(hymns.filter(h=>(h.title+' '+h.n+' '+h.author).toLowerCase().includes(s)))}
function openReader(n){current=hymns.find(x=>x.n===n);document.getElementById('rt').textContent=current.title;document.getElementById('rm').textContent=`${current.author} • ${current.year} • ${current.tune} • ${current.status}`;document.getElementById('favBtn').textContent=favorites.includes(n)?'★':'☆';
document.getElementById('sections').innerHTML=current.sections.map((s,i)=>{let rows=s.lyrics.split('\n');let notes=s.solfa||[];return `<section class="section"><h3>${s.name}</h3>${rows.map((line,j)=>`<div class="line"><div class="lyrics">${line}</div><div>${notes[j]?`<div class="solfa">${notes[j]}</div><button class="play" onclick="playSolfa('${notes[j].replace(/'/g,"\\'")}')">▶ Play</button>`:'<div class="solfa" style="opacity:.45">Sol-fa not added</div>'}</div></div>`).join('')}</section>`}).join('');document.getElementById('reader').classList.add('show')}
function closeReader(){stopSolfa();document.getElementById('reader').classList.remove('show')}
document.getElementById('favBtn').onclick=()=>{if(!current)return;favorites=favorites.includes(current.n)?favorites.filter(x=>x!==current.n):[...favorites,current.n];localStorage.setItem('ps_favs',JSON.stringify(favorites));document.getElementById('favBtn').textContent=favorites.includes(current.n)?'★':'☆'};
function playSolfa(text){stopSolfa();let map={d:261.63,r:293.66,m:329.63,f:349.23,s:392,l:440,t:493.88};let tokens=text.match(/[drmfsl t]/g)||[];let i=0,a=new AudioContext(),speed=parseFloat(document.getElementById('speed').value)||1;playing=true;timer=setInterval(()=>{if(i>=tokens.length){stopSolfa();return}let n=tokens[i++].trim();if(map[n]){let o=a.createOscillator(),g=a.createGain();o.frequency.value=map[n];g.gain.value=.045;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.25/speed)}},320/speed)}
function stopSolfa(){if(timer){clearInterval(timer);timer=null}playing=false}
document.getElementById('stop').onclick=stopSolfa;document.getElementById('theme').onclick=()=>document.body.classList.toggle('light');document.getElementById('favNav').onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));document.querySelector('[data-filter="favorites"]').classList.add('active');render(hymns.filter(h=>favorites.includes(h.n)))};
