const hymns=[
{id:"001",title:"Amazing Grace",author:"John Newton",tune:"NEW BRITAIN",cat:["worship"],sections:[
["Verse 1",[["Amazing grace! how sweet the sound",""],["That saved a wretch like me!",""],["I once was lost, but now am found;",""],["Was blind, but now I see.",""]]],
["Verse 2",[["’Twas grace that taught my heart to fear,",""],["And grace my fears relieved;",""],["How precious did that grace appear",""],["The hour I first believed!",""]]]]},
{id:"002",title:"What a Friend We Have in Jesus",author:"Joseph M. Scriven",tune:"CONVERSE",cat:["worship"],sections:[
["Verse 1",[["What a Friend we have in Jesus,",""],["All our sins and griefs to bear!",""],["What a privilege to carry",""],["Everything to God in prayer!",""]]],
["Verse 2",[["Have we trials and temptations?",""],["Is there trouble anywhere?",""],["We should never be discouraged;",""],["Take it to the Lord in prayer.",""]]]]},
{id:"003",title:"Blessed Assurance",author:"Fanny J. Crosby",tune:"ASSURANCE",cat:["worship","praise"],sections:[
["Verse 1",[["Blessed assurance, Jesus is mine!",""],["O what a foretaste of glory divine!",""],["Heir of salvation, purchase of God,",""],["Born of His Spirit, washed in His blood.",""]]],
["Chorus",[["This is my story, this is my song,",""],["Praising my Savior all the day long;",""],["This is my story, this is my song,",""],["Praising my Savior all the day long.",""]]]]}];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let filter="all",query="",current=null,shift=0,playing=false,timer;
const favs=()=>JSON.parse(localStorage.getItem("ps-favs")||"[]");
hymns.forEach(h=>h.favorite=favs().includes(h.id));
function render(){let q=query.toLowerCase();let a=hymns.filter(h=>(!q||`${h.id} ${h.title} ${h.author} ${h.tune}`.toLowerCase().includes(q))&&(filter==="all"||h.cat.includes(filter)||(filter==="favorite"&&h.favorite)));$("#count").textContent=`${a.length} hymns`;$("#empty").classList.toggle("hidden",a.length>0);$("#list").innerHTML=a.map(h=>`<article class="card"><div><p class="eyebrow">HYMN ${h.id}</p><h3>${h.title}</h3><p>${h.author} • ${h.tune} • Public domain</p></div><button class="open" onclick="openHymn('${h.id}')">Open</button></article>`).join("")}
window.openHymn=id=>{current=hymns.find(h=>h.id===id);shift=0;$("#home").classList.add("hidden");$(".library").classList.add("hidden");$("#reader").classList.remove("hidden");renderReader();scrollTo(0,0)}
function renderReader(){let h=current;$("#num").textContent=`HYMN ${h.id}`;$("#title").textContent=h.title;$("#meta").textContent=`${h.author} • ${h.tune} • Public domain`;$("#fav").textContent=h.favorite?"★":"☆";$("#sections").innerHTML=h.sections.map(s=>`<section class="song"><h3>${s[0]}</h3>${s[1].map(r=>`<div class="row"><div>${r[0]}</div><div class="solfa">${r[1]||"Sol-fa notation not supplied for this line."}</div></div>`).join("")}</section>`).join("")}
function saveFav(){let a=favs();current.favorite=!current.favorite;a=current.favorite?[...new Set([...a,current.id])]:a.filter(x=>x!==current.id);localStorage.setItem("ps-favs",JSON.stringify(a));renderReader();render()}
$("#searchInput").oninput=e=>{query=e.target.value;render()};$$(".chip").forEach(b=>b.onclick=()=>{$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});
$("#fav").onclick=saveFav;$("#back").onclick=()=>{if(playing)stop();$("#reader").classList.add("hidden");$("#home").classList.remove("hidden");$(".library").classList.remove("hidden");scrollTo(0,0)};
$("#favNav").onclick=()=>{$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.filter==="favorite"));filter="favorite";render()};
$("#themeBtn").onclick=()=>{let light=document.documentElement.dataset.theme==="light";document.documentElement.dataset.theme=light?"":"light";localStorage.setItem("ps-theme",light?"dark":"light")};if(localStorage.getItem("ps-theme")==="light")document.documentElement.dataset.theme="light";
function stop(){clearInterval(timer);playing=false;$("#play").textContent="▶ Play sol-fa"}
$("#play").onclick=()=>{if(playing){stop();return}let AC=window.AudioContext||window.webkitAudioContext;if(!AC){alert("Audio playback is not supported here.");return}let ctx=new AC(),i=0,scale=[0,2,4,5,7,9,11,12],beat=600/Number($("#speed").value);playing=true;$("#play").textContent="■ Stop";timer=setInterval(()=>{if(i>=8){stop();ctx.close();return}let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=261.63*Math.pow(2/2,(scale[i]+shift)/12);g.gain.value=.08;o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.2);i++},beat)}
$("#up").onclick=()=>{shift++;$("#meta").textContent=`${current.author} • ${current.tune} • Key +${shift}`};$("#down").onclick=()=>{shift--;$("#meta").textContent=`${current.author} • ${current.tune} • Key ${shift}`};render();